add_library(core STATIC "")
target_sources(core PRIVATE TaskManager.cpp UserManager.cpp Storage.cpp Reminder.cpp)
target_include_directories(core PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
find_package(OpenSSL REQUIRED)
find_package(nlohmann_json REQUIRED)
target_link_libraries(core OpenSSL::SSL nlohmann_json::nlohmann_json)
